store/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('storeApp.urls')),
    url(r'^admin/', admin.site.urls),
]

storeApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^product/(?P<id>[0-9]+)$',views.product,name='product'),
]

storeApp/models.py
from __future__ import unicode_literals
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=16)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=32)
    price = models.IntegerField()
    description = models.TextField()
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

storeApp/views.py
from django.http import HttpResponse
from django.template import loader

from .models import *

def index(request):
    template = loader.get_template('index.html')
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.all(),

    }
    return HttpResponse(template.render(context, request))

def product(request, id):
    template = loader.get_template('product.html')
    context = {
        'product': Product.objects.get(id=id)
    }
    return HttpResponse(template.render(context, request))

templates/index.html
<html>
    <head>
        <title>Mi tienda - Cartagena</title>
    </head>
    <body>
        {% for category in categories %}

                <h2>{{ category.name }}</h2>
                {% for product in category.product_set.all %}
                    {{ product.id }} - <a href="/product/{{ product.id }}">{{ product.name }}</a><br/>
                {% endfor %}
            {% endfor %}

    </body>
</html>

templates/product.html
<html>
    <head>
        <title>{{ product.name }} - Mis productos</title>
    </head>
    <body>
    <h1>{{ product.name }}</h1>
    <h2>{{ product.description }}</h2>
    <h3>$ {{ product.price }} COP</h3>
    <p>{{ product.description }}</p>
    </body>
</html>